<?php
// $Id$

define('WIDTH_CHAR_TO_PX', 8.0);

/**
 * Implementation of hook_views_api().
 */
function sheetnode_xls_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implementation of hook_link().
 */
function sheetnode_xls_link($type, $node = NULL, $teaser = FALSE) {
  if ($type != 'node' || $node->type != 'sheetnode') return array();

  $links['xls'] = array(
    'title' => t('XLS version'),
    'href' => 'sheetnode/xls/'. $node->nid,
  );
  $links['xlsx'] = array(
    'title' => t('XLSX version'),
    'href' => 'sheetnode/xlsx/'. $node->nid,
  );

  return $links;
}

/**
 * Implementation of hook_menu().
 */
function sheetnode_xls_menu() {
  $items = array();
    
  $items['sheetnode/xls'] = array(
    'title' => 'XLS version',
    'access arguments' => array('access content'),
    'page callback' => '_sheetnode_xls_export',
    'page arguments' => array('xls'),
    'type' => MENU_CALLBACK,
    'file' => 'sheetnode_xls.export.inc',
  );
  $items['sheetnode/xlsx'] = array(
    'title' => 'XLSX version',
    'access arguments' => array('access content'),
    'page callback' => '_sheetnode_xls_export',
    'page arguments' => array('xlsx'),
    'type' => MENU_CALLBACK,
    'file' => 'sheetnode_xls.export.inc',
  );
  $items['node/add/xls'] = array(
    'title' => 'Sheetnode import from Excel',
    'access arguments' => array('create sheetnode'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_sheetnode_xls_import_form'),
    'description' => 'Create a new sheetnode with content from an existing Excel (.xls or .xlsx) spreadsheet.',
    'file' => 'sheetnode_xls.import.inc',
  );
  $items['admin/settings/sheetnode/xls'] = array(
    'title' => 'Sheetnode XLS settings',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_sheetnode_xls_settings'),
    'description' => 'Administer settings for Sheetnode XLS.',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function _sheetnode_xls_settings() {
  $form['sheetnode_xls_jar_path'] = array(
    '#type' => 'textfield',
    '#title' => t('Apache POI files path'),
    '#description' => t('Enter the location of the extracted Apache POI package.'),
    '#default_value' => variable_get('sheetnode_xls_jar_path', ''),
  );
  $form['#submit'][] = '_sheetnode_xls_settings_submit';
  $form['#validate'][] = '_sheetnode_xls_settings_validate';
  return system_settings_form($form);
}

function _sheetnode_xls_settings_validate($form, $form_state) {
  $path = $form_state['values']['sheetnode_xls_jar_path'];
  if (!is_dir($path)) {
    form_set_error('sheetnode_xls_jar_path', t('The path you entered does not point to a valid location. Please enter the location of the extracted Apache POI package.'));
    return;
  }
}

function _sheetnode_xls_settings_submit($form, $form_state) {
  $path = $form_state['values']['sheetnode_xls_jar_path'];
  $files = file_scan_directory($path, '(.*).jar$');
  $jars = array();
  if ($files) foreach ($files as $file) {
    $jars[] = $file->filename;
  }
  variable_set('sheetnode_xls_jar', implode(';', $jars));
}

