<?php
// $Id$

define('WIDTH_CHAR_TO_PX', 8.0);

function sheetnode_xls_link($type, $node = NULL, $teaser = FALSE) {
  if ($type != 'node' || $node->type != 'sheetnode') return array();

  $links['xls'] = array(
    'title' => t('XLS version'),
    'href' => 'sheetnode/xls/'. $node->nid,
  );

  return $links;
}

function sheetnode_xls_menu() {
  $items = array();
    
  $items['sheetnode/xls'] = array(
    'title' => 'XLS version',
    'access arguments' => array('access content'),
    'page callback' => '_sheetnode_xls_export',
    'type' => MENU_CALLBACK,
    'file' => 'sheetnode_xls.export.inc',
  );
  $items['node/add/xls'] = array(
    'title' => 'Sheetnode import from XLS',
    'access arguments' => array('create sheetnode'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_sheetnode_xls_import_form'),
    'description' => 'Create a new sheetnode with content from an existing Excel (.xls) spreadsheet.',
    'file' => 'sheetnode_xls.import.inc',
  );

  return $items;
}

