<?php
// $Id$

/**
 * Implementation of hook_views_api().
 */
function sheetnode_ods_views_api() {
  return array(
    'api' => 2,
  );
}
  
/**
 * Implementation of hook_link().
 */
function sheetnode_ods_link($type, $node = NULL, $teaser = FALSE) {
  if ($type != 'node' || $node->type != 'sheetnode') return array();
/*
  $links['ods'] = array(
    'title' => t('ODS version'),
    'href' => 'sheetnode/ods/'. $node->nid,
  );
*/
  return $links;
}

/**
 * Implementation of hook_menu().
 */
function sheetnode_ods_menu() {
  $items = array();
/*    
  $items['sheetnode/ods'] = array(
    'title' => 'ODS version',
    'access arguments' => array('access content'),
    'page callback' => '_sheetnode_ods_export',
    'type' => MENU_CALLBACK,
  );
*/
  $items['node/add/ods'] = array(
    'title' => 'Sheetnode import from OOo Calc',
    'access arguments' => array('create sheetnode'),
    'page callback' => '_sheetnode_ods_import',
    'description' => 'Create a new sheetnode with content from an existing OpenOffice.org Calc (.ods) spreadsheet.',
  );
  return $items;
}

function _sheetnode_ods_import() {
  require_once(drupal_get_path('module', 'sheetnode_xls') . '/sheetnode_xls.import.inc');
  return drupal_get_form('_sheetnode_xls_import_form', t('OOCalc spreadsheet (.ods) to import'));
}

