<?php

/**
 * Implementation of hook_sheetnode_plugins().
 */
function sheetnode_ethercalc_sheetnode_plugins($value, $save_element, $context) {
  // Only turn on Ethercalc if we're editing the node.
  if (!empty($save_element)) {
    global $sheetnode_ethercalc;
    $sheetnode_ethercalc = TRUE;
  }
}

/**
 * Template preprocessor for theme('page').
 * Used to add external JavaScript files because drupal_add_js() does not support that.
 */
function sheetnode_ethercalc_preprocess_page(&$vars) {
  global $sheetnode_ethercalc;
  if (!empty($sheetnode_ethercalc)) {
    $ethercalc_host = variable_get('sheetnode_ethercalc_host', '');
    $ethercalc_port = variable_get('sheetnode_ethercalc_port', '8000');

    $ethercalc_path = $GLOBALS['base_url'];
    $ethercalc_path = preg_replace('/(:\\/\\/[^\\/]+).*/', '$1', $ethercalc_path, 1);
    if ($ethercalc_port) {
        $ethercalc_path = preg_replace('/(?:\:\d+)?$/', (':' . $ethercalc_port), $ethercalc_path, 1);
    }
    if ($ethercalc_host) {
        $ethercalc_path = preg_replace('/^([^:]*)/', $ethercalc_host, $ethercalc_path, 1);
    }

    $vars['scripts'] .= <<<EOS
<script type="text/javascript" src="$ethercalc_path/socket.io/socket.io.js#" ></script>
<script type="text/javascript" src="$ethercalc_path/zappa/zappa.js#" ></script>
<script type="text/javascript" src="$ethercalc_path/static/md5.js#" ></script>
<script type="text/javascript" src="$ethercalc_path/player/broadcast.js#" ></script>
<script type="text/javascript" src="$ethercalc_path/player/main.js#" ></script>
EOS;
  }
}

/**
 * Implementation of hook_menu().
 */
function sheetnode_ethercalc_menu() {
  $items = array();

  $items['admin/settings/sheetnode/ethercalc'] = array(
    'title' => 'EtherCalc',
    'access arguments' => array('administer site configuration'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_sheetnode_ethercalc_settings'),
    'description' => 'Administer settings for Sheetnode EtherCalc.',
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Form function for admin/settings/sheetnode/ethercalc.
 */
function _sheetnode_ethercalc_settings(&$form_state) {
  $form['sheetnode_ethercalc_host'] = array(
    '#type' => 'textfield',
    '#title' => t('EtherCalc host'),
    '#description' => t('Enter the domain name of the EtherCalc server. Leave blank to use same domain as your Drupal installation.'),
    '#default_value' => variable_get('sheetnode_ethercalc_host', ''),
  );
  $form['sheetnode_ethercalc_port'] = array(
    '#type' => 'textfield',
    '#title' => t('EtherCalc port'),
    '#description' => t('Enter the port of the EtherCalc server.'),
    '#default_value' => variable_get('sheetnode_ethercalc_port', '8000'),
  );
  return system_settings_form($form);
}

